#Evidencia de apredizaje 1: Inflación canasta de alimentos básicos en algunos páises de latinoamerica.

## I. Definición del problema de negocio

**Definición de problema y su impacto**

Según la **FAO** los precios mundiales de productos alimenticios subieron en Marzo del 2026 por segundo mes consecutivo. Debido en gran medidad por el conflicto que hay en medio oriente, el cual ha encarecido los precios enérgeticos y por ende el precio de alimentos, lo cuales cuestan más su producción. Como muestra el índice de precios subió un **2.4%** más comparado con febrero del mismo año y **1%** comparado con el promedio del año anterior. Se espera que los precios sigan subiendo a medida que el conflicto continue.

Para Latinoamerica el impacto será el mismo, el alza de precios de productos de la canasta básica, ya que la región depende de fertilizantes importados para la producción, lo cuál aumento el costo de producción y cultivo. En consecuencias estos precios se trasladan al consumidor impacto el alza del costo de vida.

De acá la importancia de analizar los precios de algunos alimentos en Colombia y compararlos con los precios de otros paises en la región.

Fuente: https://www.fao.org/newsroom/detail/fao-food-price-index-rises-in-march-as-near-east-conflict-raises-energy-costs/es

**Pregunta de investigación:**

¿Cómo varió el costo de la "Canasta de Desayuno" (Breakfast Basket) en las ciudades de Colombia comparado con el promedio regional de Latinoamérica entre octubre 2025 y marzo 2026, y qué categorías de alimentos fueron las más volátiles?

**Definición de métricas para evaluar el éxito del análisis.**

1. Puntaje de encarecimiento: Esta métrica mide el inidice de encarecemiento acumulado. Asiganandoles a todos los paises un puntaje base de 100 puntos y compara los precios a través del tiempo.

$Puntaje=(\frac{Price-USD-actual}{Price-USD-octubre-2025})*100$

2. Variación del costo de la canasta familiar: Esta métrica nos mostrara el porcentaje total de encarecmiento de los productos de la canasta básica.

$variacion=(\frac{Breakfast-Basket-Marzo2026-Breakfast-Basket-Octubre2025}{Breakfast-Basket-Octubre2025})*100$

3. Diferencia del costo de la canasta en dolares= En esta variable se va a comparar el costo en dolares de la canasta básica con el promedio de los paise de Latinoamérica.

$\text{Brecha (USD)} = \text{Breakfast-Basket-USD}_{Colombia} - \text{Promedio-Basket-USD}_{\text{Latam}}$

## II Fuente de datos

Los datos fueron encontrados en Kaggle. Nombre del dataset: Global **Grocery Inflation (2025/2026)**

Enlace del data set: https://www.kaggle.com/datasets/waddahali/global-grocery-inflation-20252026/data

**Descripción del conjunto de datos:**

* City: Nombre de la ciudad.

* Country: Nombre del país.

* ISO_Country_Code: Código internacional de 3 letras del país.

* Region: Subdivisión geográfica o región del país.

* Continent: Continente al que pertenece el país.

* Month: Fecha del registro por año y mes.

* Month_Name: Nombre completo del mes y año.

* Item: Nombre del alimento específico.

* Item_Key: ID o identificador del producto.

* Item_Category: Categoría del producto si es Lácteos, Carnes, etc..

* Price_USD: Precio del producto normalizado a dólares.

* Unit: Unidad de medida si es kg, litro, unidad.

* Currency: Moneda original antes de la conversión a dolares.

* Exchange_Rate: Valor usado para convertir la moneda local a USD.

* Inflation_Source: Fuente de los datos macroeconómicos de referencia.

* FAO_Index_Value: Valor del índice global de precios de la FAO.

* FAO_Index_Date: Fecha de publicación del índice FAO.

* FAO_YoY_Change_Pct: Variación porcentual anual del índice global.

* USDA_All_Food_Forecast_Pct: Inflación de alimentos proyectada por EE.UU.

* USDA_Food_At_Home_Pct: Inflación proyectada para comida comprada para el hogar.

* Data_Collection_Date: Día exacto en que se tomó el precio en la tienda.

* Source_URL: Enlace web a la fuente del precio.

* Population_Estimate: Cantidad de habitantes estimada de la ciudad.

* Breakfast_Basket_USD: Costo total de una canasta básica en la ciudad.

* Latitud: Coordenada de ubicación norte-sur.

* Longitud: Coordenada de ubicación este-oeste.

* Is_Capital: Indica con SI/NO si la ciudad es la capital del país.

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
df=pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQHiBq4hJEg89OqZwvtHYb1pCKtpOUGznbl4FKqyWMXuVzlgH526q71lnb8ShQSBk-50YFWT-AYMLR9/pub?gid=1722424764&single=true&output=csv")
df.head()

,City,Country,ISO_Country_Code,Region,Continent,Month,Month_Name,Item,Item_Key,Item_Category,...,Inflation_Source,FAO_Index_Value,FAO_Index_Date,FAO_YoY_Change_Pct,USDA_All_Food_Forecast_Pct,USDA_Food_At_Home_Pct,Data_Collection_Date,Source_URL,Population_Estimate,Breakfast_Basket_USD
0,New York,United States,USA,North America,North America,2025-10,October 2025,Milk (1 Liter),Milk_1L,Dairy,...,USDA Food Price Outlook / IMF WEO 2026,127.1,October 2025,-1.0,3.1,2.5,2026-03-20,https://www.numbeo.com/food-prices/in/New-York,8336817,16.18
1,New York,United States,USA,North America,North America,2025-11,November 2025,Milk (1 Liter),Milk_1L,Dairy,...,USDA Food Price Outlook / IMF WEO 2026,126.2,November 2025,-1.0,3.1,2.5,2026-03-20,https://www.numbeo.com/food-prices/in/New-York,8336817,16.40
2,New York,United States,USA,North America,North America,2025-12,December 2025,Milk (1 Liter),Milk_1L,Dairy,...,USDA Food Price Outlook / IMF WEO 2026,125.8,December 2025,-1.0,3.1,2.5,2026-03-20,https://www.numbeo.com/food-prices/in/New-York,8336817,17.02
3,New York,United States,USA,North America,North America,2026-01,January 2026,Milk (1 Liter),Milk_1L,Dairy,...,USDA Food Price Outlook / IMF WEO 2026,124.2,January 2026,-1.0,3.1,2.5,2026-03-20,https://www.numbeo.com/food-prices/in/New-York,8336817,16.80
4,New York,United States,USA,North America,North America,2026-02,February 2026,Milk (1 Liter),Milk_1L,Dairy,...,USDA Food Price Outlook / IMF WEO 2026,125.3,February 2026,-1.0,3.1,2.5,2026-03-20,https://www.numbeo.com/food-prices/in/New-York,8336817,16.82

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10248 entries, 0 to 10247
Data columns (total 27 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   City                        10248 non-null  object
 1   Country                     10248 non-null  object
 2   ISO_Country_Code            10248 non-null  object
 3   Region                      10248 non-null  object
 4   Continent                   10248 non-null  object
 5   Month                       10248 non-null  object
 6   Month_Name                  10248 non-null  object
 7   Item                        10248 non-null  object
 8   Item_Key                    10248 non-null  object
 9   Item_Category               10248 non-null  object
 10  Quantity                    10248 non-null  float64
 11  Unit                        10248 non-null  object
 12  Price_Local                 10248 non-null  float64
 13  Currency_Local              10248 non-null  object
 14  Price_USD                   10248 non-null  float64
 15  Exchange_Rate               10248 non-null  float64
 16  YoY_Inflation_Estimate_Pct  10248 non-null  float64
 17  Inflation_Source            10248 non-null  object
 18  FAO_Index_Value             10248 non-null  float64
 19  FAO_Index_Date              10248 non-null  object
 20  FAO_YoY_Change_Pct          10248 non-null  float64
 21  USDA_All_Food_Forecast_Pct  10248 non-null  float64
 22  USDA_Food_At_Home_Pct       10248 non-null  float64
 23  Data_Collection_Date        10248 non-null  object
 24  Source_URL                  10248 non-null  object
 25  Population_Estimate         10248 non-null  int64
 26  Breakfast_Basket_USD        10248 non-null  float64
dtypes: float64(10), int64(1), object(16)
memory usage: 2.1+ MB

In [19]:
pip install ydata-profiling

Requirement already satisfied: ydata-profiling in /usr/local/lib/python3.12/dist-packages (4.18.1)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.12.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /usr/local/lib/python3.12/dist-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.0.2)
Requirement already satisfied: minify-html>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.5.1)
Requirement already satisfied: imagehash==4.3.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2026.1)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.2.25)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Requirement already satisfied: puremagic in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (2.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)

In [20]:
from ydata_profiling import ProfileReport
title="Reporte de inflacion"
profile= ProfileReport(df, title=title)
profile.to_notebook_iframe()
save_as="reporte.html"
profile.to_file(save_as)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/27 [00:00<?, ?it/s]
  7%|▋         | 2/27 [00:00<00:01, 16.98it/s]
 19%|█▊        | 5/27 [00:00<00:01, 17.45it/s]
 26%|██▌       | 7/27 [00:00<00:01, 16.00it/s]
 37%|███▋      | 10/27 [00:00<00:00, 17.01it/s]
 48%|████▊     | 13/27 [00:00<00:00, 20.27it/s]
 67%|██████▋   | 18/27 [00:00<00:00, 25.41it/s]
 78%|███████▊  | 21/27 [00:01<00:00, 21.93it/s]
100%|██████████| 27/27 [00:01<00:00, 23.91it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

Observaciones del dataset:

* **Nulos**: de las 27 variables con 10248 observaciones, cada una, no se encontraron valores nulos.

* **Duplicados**: no se encontraron valores duplicados en ninguna de las variables y observaciones.

* **Tipos de datos**: entre el tipo de variables podemos encontrar 5 de tipo **texto**, 15 de tipo **categórico** y 7 **númericas**. De las cuales variables como `Month`, `Month_Name` y `Data-Collection-date` son de tipo texto u objeto, y deben ser trasnfromadas a tipo **fecha**.

* Algunas **correlaciones** importantes encontradas son:
    *  Una correlación de $1.000$ entre `Región` con `Inflation_Source` y `YoY_Inflation_Estimate_Pct` lo que indica que el calculo o la fuente de inflación esta directamente asociada la Región.
    * una correlación de $0.935$ entre`Continente` y `Región` nos habla de una jerarquía geográfica como debe experarse.
    * una correlación de $0.891$ entre `Inflation_Source` y `YoY_Inflation_Estimate_Pct` lo cual nos dice que el porcentaje de inflación depende fuertemente de la fuente de datos.
    * una correlación de $0.824$ entre `continent` y `inflation_source` lo que nos dice que la procedencia de los datos varía significativamente según el continente.
    * una correlación negativa entre `Breakfast_Basket_USD` y `YoY_Inflation_Estimate_Pc`  de $-0.601$ l oque nos dice que cuando la inflación sube, el costo de la canasta básica baja en dolares.

* Algunas **distribuciones** relvantes en las variables son:
   * `Price_USD`: esta variable presenta una asimetría positiva. La gran mayoría de los datos se concentran el los precios bajos de los productos básicos y hay una cola a la derecha generado para productos con precios elevados. Esto nos dice que la media es mayor que la mediana, es decir que los precios altos estan afectando el promedio general de los precios en dolar.
   * `YoY_Inflation_Estimate_Pct`: Muestra una distribución multimodal, es decir que tiene varios picos a lo largo de la distribución de los datos. Esto indica que la inflación esta segmentada posiblemente por regiónes con comportamientos de inflación a diferentes escalas.
   * `Breakfast_Basket_USD`: podemos obervar que la mayoría de los gastos en la canasta básica se concentran en un rango moderado de 5 a 10 dólares, mientras que los extremos altos entre 15 y 20 dólares son menos frecuentes y reflejan consumos de aliemntos caros.

## Resumen estadistico.

In [21]:
# Númericas
df.describe()

,Quantity,Price_Local,Price_USD,Exchange_Rate,YoY_Inflation_Estimate_Pct,FAO_Index_Value,FAO_YoY_Change_Pct,USDA_All_Food_Forecast_Pct,USDA_Food_At_Home_Pct,Population_Estimate,Breakfast_Basket_USD
count,10248.000000,10248.000000,10248.000000,10248.000000,10248.000000,10248.000000,10248.0,1.024800e+04,10248.0,1.024800e+04,10248.000000
mean,37.428571,3826.150373,4.479190,184.983429,5.527049,125.766667,-1.0,3.100000e+00,2.5,4.562348e+06,9.563033
std,128.331581,22062.802350,5.372603,248.290131,2.486841,0.884476,0.0,5.724589e-13,0.0,5.005719e+06,3.982560
min,1.000000,0.340000,0.170000,0.000024,2.400000,124.200000,-1.0,3.100000e+00,2.5,2.154000e+05,2.840000
25%,1.000000,4.010000,1.530000,1.082000,3.200000,125.300000,-1.0,3.100000e+00,2.5,1.208333e+06,6.847500
50%,1.000000,17.805000,2.420000,79.000000,5.500000,125.900000,-1.0,3.100000e+00,2.5,2.564854e+06,9.165000
75%,1.000000,181.557500,4.760000,252.000000,6.500000,126.200000,-1.0,3.100000e+00,2.5,6.809970e+06,11.987500
max,500.000000,325569.620000,52.130000,775.000000,11.200000,127.100000,-1.0,3.100000e+00,2.5,2.851690e+07,20.610000

* `YoY_Inflation_Estimate_Pct`:
   * conteo: 10,248 registros.
   * Promedio: 5.53%.
   * Mediana: 5.50%.
   * Desviación Estándar: 2.49%.
   * Mínimo: 2.40%.
   * Máximo: 11.20%.
  * Se observa una dispersión moderada, con valores concentrados en torno al 5–6%.
   

* `Price_USD`:
   * conteo: 10,248 registros.
   * Promedio: $4.48.
   * Mediana: $2.42.
   * Desviación Estándar: $5.37.
   * Mínimo: $0.17.
   * Máximo: $52.13.

   
* `Breakfast_Basket_USD`:

   * conteo: 10,248 registros.
   * Promedio: $9.56.
   * Mediana: $9.17.
   * Desviación Estándar: $3.98.
   * Mínimo: $2.84.
   * Máximo: $20.61.

* `FAO_Index_Value`:

  * conteo: 10,248 registros.
  * Promedio: 125.77.
  * Mediana: 125.90.
  * Desviación Estándar: 0.88.
  *	Mínimo: 124.20.
  *	Máximo: 127.10.

In [23]:
# Categóricas
df.describe(include="object")

,City,Country,ISO_Country_Code,Region,Continent,Month,Month_Name,Item,Item_Key,Item_Category,Unit,Currency_Local,Inflation_Source,FAO_Index_Date,Data_Collection_Date,Source_URL
count,10248,10248,10248,10248,10248,10248,10248,10248,10248,10248,10248,10248,10248,10248,10248,10248
unique,122,80,80,12,6,6,6,14,14,7,5,63,8,6,1,122
top,New York,United States,USA,Western Europe,Asia,2025-10,October 2025,Milk (1 Liter),Milk_1L,Vegetables,kg,EUR,IMF WEO 2026,October 2025,2026-03-20,https://www.numbeo.com/food-prices/in/New-York
freq,84,504,504,2016,3612,1708,1708,732,732,2928,7320,1932,3276,1708,10248,84

* `Continent`:

  * conteo : 11,540 registros.
  * Moda : Asia
  * freq: 3612

* `Currency_local`:

  * conteo: 11,540 registros.
  * Moda : EUR.
  * freq: 1932

* `Item`

   * conteo:11,540 registros.
   * Moda: Milk (1 Liter).
   * freq: 732